### ISSUE TITLE
How to use this image? The script exits saying varnishstats is not found

### ISSUE THREAD

**Issue by aluxian** [jangrewe/docker-varnish-exporter#1]
Hey, thanks for this image! I have a question, though:

How do you use it? Whenever I start it, it says it cannot find `varnishstats`.

Thanks!

**Comment by comotion** [comment]
This docker image does not make any sense. varnishstats has to be run on the same box as varnish itself, with access to the shared memory file of that varnish instance. How to do this with docker?

**Comment by aluxian** [comment]
I don't know about you, but I found a solution eventually. 

**Varnish exporter:**

```
exporter-varnish:
  image: 'jangrewe/varnish-exporter:latest'
  environment:
    - VARNISH_CONTAINER_NAME=varnish-1.main
  restart: on-failure
  volumes:
    - '/mnt/data/monit/varnish/varnishstat:/usr/bin/varnishstat:ro'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '/usr/bin/docker:/usr/bin/docker:ro'
```

**Varnish:**

```
varnish:
  image: 'million12/varnish:latest'
  environment:
    - CACHE_SIZE=768m
    - 'VARNISHD_PARAMS=-p default_grace=3600'
  links:
    - haproxy
  ports:
    - '80:80'
  restart: on-failure
  volumes:
    - '/mnt/data/main/varnish:/etc/varnish'
```

**/mnt/data/monit/varnish/varnishstat** (don't forget to `chmod +x` it)

```
#!/bin/sh

exec docker exec $(docker ps -qf "name=$VARNISH_CONTAINER_NAME" | head -n 1) varnishstat "$@"
```

Basically, I replaced varnishstat in your container image to use `docker exec` to run `varnishstat` inside my varnish container.
