### ISSUE TITLE
executable file not found in $PATH on boot up of sidecar 

### ISSUE THREAD

**Issue by woutersf** [jangrewe/docker-varnish-exporter#2]
Thanks for the container! 

When I create this as a sidecar (in kubernetes on aks): I get the following:
`[FATAL] Varnish version initialize failed: exec: “varnishstat”: executable file not found in $PATH`

I'm using docker image varnish:6.4. 
I think the 6.4 image does have a varnishstat execuable (/usr/bin/varnishstat).

How to fix this?

this is how I add them in my helm charts: 

```
      containers:
      - name: {{.Release.Name}}-varnish
        image: varnish:6.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/varnish/default.vcl
          name: varnish-vcl
          subPath: default.vcl

      {{ if eq .Values.exporter.varnish.enabled true }}
      - name: varnish-exporter
        image: jangrewe/varnish-exporter
        ports:
        - containerPort: 9253
          protocol: TCP
          name: varnish-metrics
        resources: 
          {{ include "drupal.exporter.resources" . | nindent 11 }}
        {{ end }}
            
```
